package io.github.kawase.packet;

import io.github.kawase.exceptions.PacketException;
import io.github.kawase.packet.impl.ai.AiResponsePacket;
import io.github.kawase.packet.impl.ai.AskAiPacket;
import io.github.kawase.packet.impl.ai.GenerateAiTaskPacket;
import io.github.kawase.packet.impl.ai.GenerateAiTaskResponsePacket;
import io.github.kawase.packet.impl.companion.CompanionSpeakPacket;
import io.github.kawase.packet.impl.companion.CompanionSpeakResponsePacket;
import io.github.kawase.packet.impl.companion.CompanionVoiceAudioPacket;
import io.github.kawase.packet.impl.companion.CompanionVoiceTextPacket;
import io.github.kawase.packet.impl.auth.*;
import io.github.kawase.packet.impl.child.*;
import io.github.kawase.packet.impl.course.FetchCourseDetailPacket;
import io.github.kawase.packet.impl.course.FetchCourseDetailResponsePacket;
import io.github.kawase.packet.impl.course.FetchPublishedCoursesPacket;
import io.github.kawase.packet.impl.course.FetchPublishedCoursesResponsePacket;
import io.github.kawase.packet.impl.course.SubmitCourseCompletionPacket;
import io.github.kawase.packet.impl.core.*;
import io.github.kawase.packet.impl.game.*;
import io.github.kawase.packet.impl.language.ExecuteCPPCodePacket;
import io.github.kawase.packet.impl.language.ExecuteCPPCodeResponsePacket;
import io.github.kawase.packet.impl.language.ExecutePythonCodePacket;
import io.github.kawase.packet.impl.language.ExecutePythonCodeResponsePacket;
import io.github.kawase.packet.impl.qr.*;

public class PacketManager {
    public Packet createPacket(final int id) {
        return switch (id) {
            case 1 -> new HandShakePacket();
            case 2 -> new AuthPacket();
            case 3 -> new RegisterParentPacket();
            case 4 -> new AddChildPacket();
            case 5 -> new AddGoalPacket();
            case 8 -> new CompleteTaskPacket();
            case 9 -> new ActionResponsePacket();
            case 10 -> new AuthResponsePacket();
            case 11 -> new FetchTasksPacket();
            case 12 -> new FetchTasksResponsePacket();
            case 13 -> new FetchGoalsPacket();
            case 14 -> new FetchGoalsResponsePacket();
            case 15 -> new FetchChildrenPacket();
            case 16 -> new FetchChildrenResponsePacket();
            case 17 -> new FetchCompletedTasksPacket();
            case 18 -> new FetchCompletedTasksResponsePacket();
            case 19 -> new GenerateQRLoginPacket();
            case 20 -> new QRLoginResponsePacket();
            case 21 -> new ClaimQRLoginPacket();
            case 22 -> new ChildAuthResponsePacket();
            case 23 -> new FetchChildStatsPacket();
            case 24 -> new FetchChildStatsResponsePacket();
            case 25 -> new VerifySessionPacket();
            case 26 -> new UpdatePfpPacket();
            case 27 -> new RemoveChildPacket();
            case 28 -> new ExecuteCPPCodePacket();
            case 29 -> new ExecuteCPPCodeResponsePacket();
            case 30 -> new AskAiPacket();
            case 31 -> new AiResponsePacket();
            case 32 -> new FetchChildStatsByParentPacket();
            case 33 -> new RecordLearningEventPacket();
            case 34 -> new ExecutePythonCodePacket();
            case 35 -> new ExecutePythonCodeResponsePacket();
            case 36 -> new FetchPublishedCoursesPacket();
            case 37 -> new FetchPublishedCoursesResponsePacket();
            case 38 -> new FetchCourseDetailPacket();
            case 39 -> new FetchCourseDetailResponsePacket();
            case 40 -> new SubmitCourseCompletionPacket();
            case 41 -> new FetchAllChildrenPacket();
            case 42 -> new FetchAllChildrenResponsePacket();
            case 43 -> new DevLoginAsChildPacket();
            case 44 -> new DevCreateChildProfilePacket();
            case 45 -> new GenerateAiTaskPacket();
            case 46 -> new GenerateAiTaskResponsePacket();
            case 47 -> new CompanionSpeakPacket();
            case 48 -> new CompanionSpeakResponsePacket();
            case 58 -> new CompanionVoiceTextPacket();
            case 59 -> new CompanionVoiceAudioPacket();
            case 64 -> new SubscribeLiveSessionPacket();
            case 65 -> new LiveSessionUpdatePacket();
            case 66 -> new SendParentChallengePacket();
            case 67 -> new ParentChallengePacket();
            case 68 -> new ParentChallengeCompletedPacket();
            case 69 -> new FetchWeeklyReportPacket();
            case 70 -> new WeeklyReportResponsePacket();
            case 71 -> new FetchProgrammingProfileSummaryPacket();
            case 72 -> new FetchProgrammingProfileSummaryResponsePacket();

            default -> throw new PacketException("Unknown packet ID: " + id);
        };
    }
}
