package io.github.kawase.packet;

import io.github.kawase.exceptions.PacketException;
import io.github.kawase.packet.impl.ai.AiResponsePacket;
import io.github.kawase.packet.impl.ai.AskAiPacket;
import io.github.kawase.packet.impl.ai.GenerateAiTaskPacket;
import io.github.kawase.packet.impl.ai.GenerateAiTaskResponsePacket;
import io.github.kawase.packet.impl.auth.AuthPacket;
import io.github.kawase.packet.impl.auth.AuthResponsePacket;
import io.github.kawase.packet.impl.auth.BeginParentTotpEnrollmentPacket;
import io.github.kawase.packet.impl.auth.ConfirmParentTotpEnrollmentPacket;
import io.github.kawase.packet.impl.auth.DisableParentTotpPacket;
import io.github.kawase.packet.impl.auth.FetchParentSecurityStatusPacket;
import io.github.kawase.packet.impl.auth.ParentAuthSessionPacket;
import io.github.kawase.packet.impl.auth.ParentSecondFactorRequiredPacket;
import io.github.kawase.packet.impl.auth.ParentSecurityStatusPacket;
import io.github.kawase.packet.impl.auth.ParentTotpEnrollmentDetailsPacket;
import io.github.kawase.packet.impl.auth.ParentTotpEnrollmentResultPacket;
import io.github.kawase.packet.impl.auth.RegisterParentPacket;
import io.github.kawase.packet.impl.auth.ResumeParentSessionPacket;
import io.github.kawase.packet.impl.auth.RevokeParentSessionPacket;
import io.github.kawase.packet.impl.auth.VerifyParentSecondFactorPacket;
import io.github.kawase.packet.impl.child.AddChildPacket;
import io.github.kawase.packet.impl.child.DevCreateChildProfilePacket;
import io.github.kawase.packet.impl.child.DevLoginAsChildPacket;
import io.github.kawase.packet.impl.child.FetchAllChildrenPacket;
import io.github.kawase.packet.impl.child.FetchAllChildrenResponsePacket;
import io.github.kawase.packet.impl.child.FetchChildStatsByParentPacket;
import io.github.kawase.packet.impl.child.FetchChildStatsPacket;
import io.github.kawase.packet.impl.child.FetchChildStatsResponsePacket;
import io.github.kawase.packet.impl.child.FetchChildrenPacket;
import io.github.kawase.packet.impl.child.FetchChildrenResponsePacket;
import io.github.kawase.packet.impl.child.FetchProgrammingProfileSummaryPacket;
import io.github.kawase.packet.impl.child.FetchProgrammingProfileSummaryResponsePacket;
import io.github.kawase.packet.impl.child.RemoveChildPacket;
import io.github.kawase.packet.impl.child.UpdatePfpPacket;
import io.github.kawase.packet.impl.companion.CompanionSpeakPacket;
import io.github.kawase.packet.impl.companion.CompanionSpeakResponsePacket;
import io.github.kawase.packet.impl.companion.CompanionVoiceAudioPacket;
import io.github.kawase.packet.impl.companion.CompanionVoiceTextPacket;
import io.github.kawase.packet.impl.course.FetchCourseDetailPacket;
import io.github.kawase.packet.impl.course.FetchCourseDetailResponsePacket;
import io.github.kawase.packet.impl.course.FetchPublishedCoursesPacket;
import io.github.kawase.packet.impl.course.FetchPublishedCoursesResponsePacket;
import io.github.kawase.packet.impl.course.SubmitCourseCompletionPacket;
import io.github.kawase.packet.impl.core.ActionResponsePacket;
import io.github.kawase.packet.impl.core.HandShakePacket;
import io.github.kawase.packet.impl.core.SetClientLanguagePacket;
import io.github.kawase.packet.impl.game.AddGoalPacket;
import io.github.kawase.packet.impl.game.CompleteTaskPacket;
import io.github.kawase.packet.impl.game.FetchCompletedTasksPacket;
import io.github.kawase.packet.impl.game.FetchCompletedTasksResponsePacket;
import io.github.kawase.packet.impl.game.FetchGoalsPacket;
import io.github.kawase.packet.impl.game.FetchGoalsResponsePacket;
import io.github.kawase.packet.impl.game.FetchTasksPacket;
import io.github.kawase.packet.impl.game.FetchTasksResponsePacket;
import io.github.kawase.packet.impl.game.FetchWeeklyReportPacket;
import io.github.kawase.packet.impl.game.LiveSessionUpdatePacket;
import io.github.kawase.packet.impl.game.ParentChallengeCompletedPacket;
import io.github.kawase.packet.impl.game.ParentChallengePacket;
import io.github.kawase.packet.impl.game.RecordLearningEventPacket;
import io.github.kawase.packet.impl.game.SendParentChallengePacket;
import io.github.kawase.packet.impl.game.SubscribeLiveSessionPacket;
import io.github.kawase.packet.impl.game.WeeklyReportResponsePacket;
import io.github.kawase.packet.impl.language.CodeWorldPythonResponsePacket;
import io.github.kawase.packet.impl.language.CodeWorldPythonRunPacket;
import io.github.kawase.packet.impl.language.ExecuteCPPCodePacket;
import io.github.kawase.packet.impl.language.ExecuteCPPCodeResponsePacket;
import io.github.kawase.packet.impl.language.ExecutePythonCodePacket;
import io.github.kawase.packet.impl.language.ExecutePythonCodeResponsePacket;
import io.github.kawase.packet.impl.machinelearning.FetchMachineLearningProblemsPacket;
import io.github.kawase.packet.impl.machinelearning.MachineLearningProblemsResponsePacket;
import io.github.kawase.packet.impl.machinelearning.MachineLearningSubmissionResultPacket;
import io.github.kawase.packet.impl.machinelearning.SubmitMachineLearningSolutionPacket;
import io.github.kawase.packet.impl.qr.ChildAuthResponsePacket;
import io.github.kawase.packet.impl.qr.ClaimQRLoginPacket;
import io.github.kawase.packet.impl.qr.GenerateQRLoginPacket;
import io.github.kawase.packet.impl.qr.QRLoginResponsePacket;
import io.github.kawase.packet.impl.qr.VerifySessionPacket;

public class PacketManager {
    public Packet createPacket(final int id) {
        return switch (id) {
            case 1 -> new HandShakePacket();
            case 2 -> new AuthPacket();
            case 3 -> new RegisterParentPacket();
            case 4 -> new AddChildPacket();
            case 5 -> new AddGoalPacket();
            case 8 -> new CompleteTaskPacket();
            case 9 -> new ActionResponsePacket();
            case 10 -> new AuthResponsePacket();
            case 11 -> new FetchTasksPacket();
            case 12 -> new FetchTasksResponsePacket();
            case 13 -> new FetchGoalsPacket();
            case 14 -> new FetchGoalsResponsePacket();
            case 15 -> new FetchChildrenPacket();
            case 16 -> new FetchChildrenResponsePacket();
            case 17 -> new FetchCompletedTasksPacket();
            case 18 -> new FetchCompletedTasksResponsePacket();
            case 19 -> new GenerateQRLoginPacket();
            case 20 -> new QRLoginResponsePacket();
            case 21 -> new ClaimQRLoginPacket();
            case 22 -> new ChildAuthResponsePacket();
            case 23 -> new FetchChildStatsPacket();
            case 24 -> new FetchChildStatsResponsePacket();
            case 25 -> new VerifySessionPacket();
            case 26 -> new UpdatePfpPacket();
            case 27 -> new RemoveChildPacket();
            case 28 -> new ExecuteCPPCodePacket();
            case 29 -> new ExecuteCPPCodeResponsePacket();
            case 30 -> new AskAiPacket();
            case 31 -> new AiResponsePacket();
            case 32 -> new FetchChildStatsByParentPacket();
            case 33 -> new RecordLearningEventPacket();
            case 34 -> new ExecutePythonCodePacket();
            case 35 -> new ExecutePythonCodeResponsePacket();
            case 36 -> new FetchPublishedCoursesPacket();
            case 37 -> new FetchPublishedCoursesResponsePacket();
            case 38 -> new FetchCourseDetailPacket();
            case 39 -> new FetchCourseDetailResponsePacket();
            case 40 -> new SubmitCourseCompletionPacket();
            case 41 -> new FetchAllChildrenPacket();
            case 42 -> new FetchAllChildrenResponsePacket();
            case 43 -> new DevLoginAsChildPacket();
            case 44 -> new DevCreateChildProfilePacket();
            case 45 -> new GenerateAiTaskPacket();
            case 46 -> new GenerateAiTaskResponsePacket();
            case 47 -> new CompanionSpeakPacket();
            case 48 -> new CompanionSpeakResponsePacket();
            case 58 -> new CompanionVoiceTextPacket();
            case 59 -> new CompanionVoiceAudioPacket();
            case 64 -> new SubscribeLiveSessionPacket();
            case 65 -> new LiveSessionUpdatePacket();
            case 66 -> new SendParentChallengePacket();
            case 67 -> new ParentChallengePacket();
            case 68 -> new ParentChallengeCompletedPacket();
            case 69 -> new FetchWeeklyReportPacket();
            case 70 -> new WeeklyReportResponsePacket();
            case 71 -> new FetchProgrammingProfileSummaryPacket();
            case 72 -> new FetchProgrammingProfileSummaryResponsePacket();
            case 74 -> new CodeWorldPythonRunPacket();
            case 75 -> new CodeWorldPythonResponsePacket();
            case 76 -> new SetClientLanguagePacket();
            case 77 -> new FetchMachineLearningProblemsPacket();
            case 78 -> new MachineLearningProblemsResponsePacket();
            case 79 -> new SubmitMachineLearningSolutionPacket();
            case 80 -> new MachineLearningSubmissionResultPacket();
            case 81 -> new ParentSecondFactorRequiredPacket();
            case 82 -> new VerifyParentSecondFactorPacket();
            case 83 -> new BeginParentTotpEnrollmentPacket();
            case 84 -> new ParentTotpEnrollmentDetailsPacket();
            case 85 -> new ConfirmParentTotpEnrollmentPacket();
            case 86 -> new ParentTotpEnrollmentResultPacket();
            case 87 -> new DisableParentTotpPacket();
            case 88 -> new FetchParentSecurityStatusPacket();
            case 89 -> new ParentSecurityStatusPacket();
            case 90 -> new ParentAuthSessionPacket();
            case 91 -> new ResumeParentSessionPacket();
            case 92 -> new RevokeParentSessionPacket();

            default -> throw new PacketException("Unknown packet ID: " + id);
        };
    }
}
